version: '3.8'
services:
  nestjs:
    container_name: nestjs_container
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      DB_HOST: pg_container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_DATABASE: nestjs-task-app

  postgres:
    image: postgres:alpine
    container_name: pg_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      TZ: 'Asia/Thailand'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    container_name: pgadmin4_container
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_USER: pgadmin4
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin4-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin4-data:
